// Never Too Late Games

#pragma once

#include "NativeGameplayTags.h"

namespace FrontendGameplayTags
{

	// Frontend Widget Stack Tags
	FRONTENDTEMPLATE_CUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_WidgetStack_Modal);
	FRONTENDTEMPLATE_CUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_WidgetStack_GameMenu);
	FRONTENDTEMPLATE_CUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_WidgetStack_GameHud);
	FRONTENDTEMPLATE_CUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_WidgetStack_Frontend);

	// Frontend Widget Tags
	FRONTENDTEMPLATE_CUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_Widget_PressAnyScreen);
	FRONTENDTEMPLATE_CUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_Widget_MainMenuScreen);
	FRONTENDTEMPLATE_CUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_Widget_OptionsScreen);

	FRONTENDTEMPLATE_CUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_Widget_ConfirmScreen);
	FRONTENDTEMPLATE_CUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN
	(Frontend_Widget_KeyRemapScreen);


	// Frontend Options Image Tags
	FRONTENDTEMPLATE_CUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_Image_TestImage);
	FRONTENDTEMPLATE_CUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Frontend_Image_TestImage2);

}